apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: mysql-container
          image: datascientest/mysql-k8s:1.0.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password-secret
                  key: password
        - name: fastapi-container
          image: azizivakili/datascientestapi:1.0
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password-secret
                  key: password
          ports:
            - containerPort: 8000
