apiVersion: v1
kind: Secret
metadata:
  name: mysql-password-secret
type: Opaque
data:
  password: ZGF0YXNjaWVudGVzdDEyMzQ=  # Base64 encoded value of 'datascientest1234'


# Please NOTE: we can generate the above password by following code:

# echo -n 'datascientest1234' | base64
